<template>
  <div class="ai-ppt-gen">
    <div class="header">
      <div class="logo">AI PPT <span class="highlight">Generator</span></div>
      <div class="actions">
        <button class="action-btn" @click="reset" v-if="step > 1">New Project</button>
        <button class="action-btn close" @click="goHome">Exit</button>
      </div>
    </div>

    <div class="main-content">
      <!-- Step 1: Topic Input -->
      <transition name="fade" mode="out-in">
        <div v-if="step === 1" class="step-container input-step" key="step1">
          <div class="hero-text">
            <h1>Turn Ideas into <br /><span class="gradient-text">Presentation</span></h1>
            <p>Enter your topic, and let our AI craft the perfect slide deck for you.</p>
          </div>

          <div class="input-box">
            <input
              v-model="topic"
              type="text"
              placeholder="e.g., The Future of Renewable Energy"
              @keyup.enter="generateOutline"
            />
            <button class="generate-btn" @click="generateOutline" :disabled="!topic || isLoading">
              <span v-if="!isLoading">Generate Outline</span>
              <span v-else>Processing...</span>
            </button>
          </div>

          <div class="suggestions">
            <span>Try:</span>
            <button @click="topic = 'Digital Marketing Trends 2025'">
              Digital Marketing Trends
            </button>
            <button @click="topic = 'Introduction to Quantum Computing'">Quantum Computing</button>
            <button @click="topic = 'Sustainable Urban Planning'">Urban Planning</button>
          </div>
        </div>

        <!-- Step 2: Outline Editor -->
        <div v-else-if="step === 2" class="step-container outline-step" key="step2">
          <div class="step-header">
            <h2>Review Outline</h2>
            <p>Customize the structure before generating slides.</p>
          </div>

          <div class="outline-list">
            <div v-for="(slide, index) in outline" :key="index" class="outline-item">
              <div class="slide-number">{{ index + 1 }}</div>
              <div class="slide-content-edit">
                <input v-model="slide.title" class="slide-title-input" placeholder="Slide Title" />
                <textarea
                  v-model="slide.content"
                  class="slide-bullets-input"
                  placeholder="Key points (one per line)"
                  rows="3"
                ></textarea>
              </div>
              <button class="remove-btn" @click="removeSlide(index)">×</button>
            </div>
            <button class="add-slide-btn" @click="addSlide">+ Add Slide</button>
          </div>

          <div class="step-actions">
            <button class="secondary-btn" @click="step = 1">Back</button>
            <button class="primary-btn" @click="generateSlides">Generate Slides</button>
          </div>
        </div>

        <!-- Step 3: Slide Editor -->
        <div v-else-if="step === 3" class="step-container editor-step" key="step3">
          <div class="editor-layout">
            <!-- Sidebar: Thumbnails -->
            <div class="thumbnails-sidebar">
              <div
                v-for="(slide, index) in outline"
                :key="index"
                class="thumbnail"
                :class="{ active: currentSlideIndex === index }"
                @click="currentSlideIndex = index"
              >
                <div class="thumb-preview">
                  <div class="thumb-title">{{ slide.title }}</div>
                  <div class="thumb-content-preview">
                    <div
                      v-for="line in slide.content.split('\n').slice(0, 3)"
                      :key="line"
                      class="thumb-line"
                    ></div>
                  </div>
                </div>
                <span class="thumb-num">{{ index + 1 }}</span>
              </div>
            </div>

            <!-- Main Editor -->
            <div class="slide-workspace">
              <div class="slide-canvas">
                <div class="slide-content">
                  <input
                    v-model="outline[currentSlideIndex].title"
                    class="editor-title"
                    placeholder="Slide Title"
                  />
                  <div class="editor-body">
                    <textarea
                      v-model="outline[currentSlideIndex].content"
                      class="editor-text-area"
                      placeholder="Enter bullet points here..."
                    ></textarea>
                  </div>
                </div>
                <div class="slide-footer">
                  <span class="footer-text">Generated by AI PPT</span>
                  <span class="slide-number-display"
                    >{{ currentSlideIndex + 1 }} / {{ outline.length }}</span
                  >
                </div>
              </div>

              <div class="editor-controls">
                <div class="nav-controls">
                  <button
                    class="nav-btn"
                    @click="currentSlideIndex > 0 ? currentSlideIndex-- : null"
                    :disabled="currentSlideIndex === 0"
                  >
                    Previous
                  </button>
                  <button
                    class="nav-btn"
                    @click="currentSlideIndex < outline.length - 1 ? currentSlideIndex++ : null"
                    :disabled="currentSlideIndex === outline.length - 1"
                  >
                    Next
                  </button>
                </div>
                <button class="export-btn" @click="exportPPT">
                  <span class="icon">⬇️</span> Export PPTX
                </button>
              </div>
            </div>
          </div>
        </div>
      </transition>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import pptxgen from 'pptxgenjs';

const router = useRouter();
const step = ref(1);
const topic = ref('');
const isLoading = ref(false);
const currentSlideIndex = ref(0);

interface Slide {
  title: string;
  content: string; // Newline separated bullets
}

const outline = ref<Slide[]>([]);

const goHome = () => {
  router.push('/');
};

const reset = () => {
  step.value = 1;
  topic.value = '';
  outline.value = [];
  currentSlideIndex.value = 0;
};

// Real AI Outline Generation
const generateOutline = async () => {
  if (!topic.value) return;
  isLoading.value = true;

  try {
    const prompt = `Act as a professional presentation consultant. Create a detailed and structured presentation outline for the topic: "${topic.value}".
    
    Target Audience: General Professional
    Tone: Informative and Engaging
    
    Structure Requirements:
    1. Title Slide: Catchy title and subtitle
    2. Introduction: Hook, context, and thesis
    3. Problem/Context: Why this topic matters now
    4. Main Points (3-4 slides): Deep dive into key concepts with specific examples
    5. Future Trends/Implications: Forward-looking perspective
    6. Conclusion: Summary and Call to Action
    
    Output Format:
    Return ONLY a valid JSON array of objects. No markdown, no explanations.
    Each object must strictly follow this schema:
    {
      "title": "Slide Title",
      "content": "Bullet point 1\\nBullet point 2\\nBullet point 3"
    }
    
    Ensure the content is detailed (at least 3-5 bullet points per slide).`;

    const response = await fetch('http://localhost:8080/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ prompt })
    });

    if (!response.ok) {
      throw new Error(`API Error: ${response.status}`);
    }

    const data = await response.json();

    // Parse the AI response
    // The Gemini API structure returns data.candidates[0].content.parts[0].text
    if (
      data.candidates &&
      data.candidates[0] &&
      data.candidates[0].content &&
      data.candidates[0].content.parts
    ) {
      let text = data.candidates[0].content.parts[0].text;

      // Clean up potential markdown code blocks if the prompt instruction failed
      text = text
        .replace(/```json/g, '')
        .replace(/```/g, '')
        .trim();

      try {
        const slides = JSON.parse(text);
        if (Array.isArray(slides)) {
          outline.value = slides;
          step.value = 2;
        } else {
          console.error('AI response is not an array:', slides);
          alert('Failed to parse AI response structure.');
        }
      } catch (e) {
        console.error('JSON Parse Error:', e);
        console.log('Raw Text:', text);
        alert('Failed to parse AI response as JSON.');
      }
    } else {
      console.error('Unexpected API response structure:', data);
      alert('AI Generation failed. Please try again.');
    }
  } catch (error) {
    console.error('Error generating outline:', error);
    alert('Failed to generate outline. Is the backend running?');
  } finally {
    isLoading.value = false;
  }
};

const removeSlide = (index: number) => {
  outline.value.splice(index, 1);
};

const addSlide = () => {
  outline.value.push({ title: 'New Slide', content: 'Add your content here' });
};

const generateSlides = () => {
  // In a real app, this might generate images or layout configurations
  // For now, we just move to the editor view
  step.value = 3;
  currentSlideIndex.value = 0;
};

const exportPPT = () => {
  const pres = new pptxgen();

  // Set Presentation metadata
  pres.title = topic.value;

  // Define a master slide (template)
  pres.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: 'FFFFFF' },
    objects: [
      { rect: { x: 0, y: 0, w: '100%', h: 0.8, fill: { color: '000000' } } }, // Top bar
      {
        text: {
          text: 'AI Generated Presentation',
          options: { x: 0.5, y: 0.2, w: 8, h: 0.4, color: 'FFFFFF', fontSize: 14 }
        }
      }
    ]
  });

  outline.value.forEach((slide) => {
    const pptSlide = pres.addSlide();

    // Title
    pptSlide.addText(slide.title, {
      x: 0.5,
      y: 0.5,
      w: '90%',
      h: 1,
      fontSize: 32,
      bold: true,
      color: '363636',
      fontFace: 'Arial'
    });

    // Content (Bullets)
    const bullets = slide.content.split('\n').filter((line) => line.trim() !== '');
    const bulletItems = bullets.map((b) => ({
      text: b,
      options: { fontSize: 18, breakLine: true }
    }));

    if (bulletItems.length > 0) {
      pptSlide.addText(bulletItems, {
        x: 0.5,
        y: 1.8,
        w: '90%',
        h: 4,
        fontSize: 18,
        color: '666666',
        bullet: true,
        lineSpacing: 30
      });
    }

    // Add a subtle footer
    pptSlide.addText('Generated by AI PPT', {
      x: 0.5,
      y: 5.2,
      w: '90%',
      h: 0.3,
      fontSize: 10,
      color: 'CCCCCC',
      align: 'center'
    });
  });

  pres.writeFile({ fileName: `${topic.value.replace(/\s+/g, '_')}_Presentation.pptx` });
};
</script>

<style scoped>
.ai-ppt-gen {
  min-height: 100vh;
  background: #0f172a;
  color: #f8fafc;
  font-family: 'Inter', sans-serif;
  display: flex;
  flex-direction: column;
}

.header {
  height: 70px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 40px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  background: rgba(15, 23, 42, 0.8);
  backdrop-filter: blur(10px);
  position: sticky;
  top: 0;
  z-index: 100;
}

.logo {
  font-size: 1.5rem;
  font-weight: 700;
  letter-spacing: -0.02em;
}

.highlight {
  color: #38bdf8;
}

.action-btn {
  background: transparent;
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #fff;
  padding: 8px 16px;
  border-radius: 6px;
  cursor: pointer;
  margin-left: 12px;
  transition: all 0.2s;
}

.action-btn:hover {
  background: rgba(255, 255, 255, 0.1);
}

.action-btn.close {
  border-color: #ef4444;
  color: #ef4444;
}

.action-btn.close:hover {
  background: #ef4444;
  color: #fff;
}

.main-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  position: relative;
}

.step-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px 20px;
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
}

/* Step 1 Styles */
.input-step {
  justify-content: center;
  padding-bottom: 120px;
}

.hero-text {
  text-align: center;
  margin-bottom: 60px;
}

.hero-text h1 {
  font-size: 4rem;
  line-height: 1.1;
  margin-bottom: 20px;
}

.gradient-text {
  background: linear-gradient(to right, #38bdf8, #818cf8);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.hero-text p {
  font-size: 1.2rem;
  color: #94a3b8;
}

.input-box {
  display: flex;
  width: 100%;
  max-width: 700px;
  background: rgba(30, 41, 59, 0.5);
  border: 1px solid rgba(255, 255, 255, 0.1);
  padding: 8px;
  border-radius: 16px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.3);
}

.input-box input {
  flex: 1;
  background: transparent;
  border: none;
  padding: 16px 24px;
  font-size: 1.1rem;
  color: #fff;
  outline: none;
}

.generate-btn {
  background: linear-gradient(135deg, #38bdf8, #6366f1);
  border: none;
  color: #fff;
  padding: 0 32px;
  border-radius: 12px;
  font-weight: 600;
  cursor: pointer;
  transition: transform 0.2s;
}

.generate-btn:hover {
  transform: translateY(-1px);
}

.generate-btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.suggestions {
  margin-top: 24px;
  display: flex;
  gap: 12px;
  align-items: center;
  color: #64748b;
}

.suggestions button {
  background: rgba(30, 41, 59, 0.5);
  border: 1px solid rgba(255, 255, 255, 0.05);
  color: #94a3b8;
  padding: 6px 12px;
  border-radius: 100px;
  cursor: pointer;
  transition: all 0.2s;
}

.suggestions button:hover {
  background: #38bdf8;
  color: #0f172a;
}

/* Step 2 Styles */
.outline-step {
  width: 100%;
  max-width: 800px;
}

.step-header {
  text-align: center;
  margin-bottom: 40px;
}

.outline-list {
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.outline-item {
  display: flex;
  gap: 16px;
  background: rgba(30, 41, 59, 0.4);
  padding: 20px;
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.05);
}

.slide-number {
  width: 32px;
  height: 32px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  color: #38bdf8;
  flex-shrink: 0;
}

.slide-content-edit {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.slide-title-input {
  background: transparent;
  border: none;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  color: #fff;
  font-size: 1.1rem;
  font-weight: 600;
  padding: 4px 0;
  outline: none;
}

.slide-bullets-input {
  background: transparent;
  border: 1px solid rgba(255, 255, 255, 0.05);
  color: #cbd5e1;
  padding: 8px;
  border-radius: 4px;
  resize: vertical;
  font-family: inherit;
  outline: none;
}

.slide-bullets-input:focus {
  border-color: #38bdf8;
}

.remove-btn {
  background: transparent;
  border: none;
  color: #64748b;
  font-size: 1.5rem;
  cursor: pointer;
  align-self: flex-start;
}

.remove-btn:hover {
  color: #ef4444;
}

.add-slide-btn {
  background: transparent;
  border: 2px dashed rgba(255, 255, 255, 0.1);
  color: #94a3b8;
  padding: 16px;
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.2s;
}

.add-slide-btn:hover {
  border-color: #38bdf8;
  color: #38bdf8;
}

.step-actions {
  display: flex;
  justify-content: flex-end;
  gap: 16px;
  width: 100%;
  margin-top: 40px;
}

.primary-btn,
.secondary-btn {
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.primary-btn {
  background: #38bdf8;
  border: none;
  color: #0f172a;
}

.primary-btn:hover {
  background: #0ea5e9;
}

.secondary-btn {
  background: transparent;
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #fff;
}

.secondary-btn:hover {
  background: rgba(255, 255, 255, 0.05);
}

/* Step 3 Styles */
.editor-step {
  padding: 0;
  max-width: none;
  height: calc(100vh - 70px);
}

.editor-layout {
  display: flex;
  width: 100%;
  height: 100%;
}

.thumbnails-sidebar {
  width: 250px;
  background: rgba(15, 23, 42, 0.5);
  border-right: 1px solid rgba(255, 255, 255, 0.1);
  padding: 20px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.thumbnail {
  cursor: pointer;
  display: flex;
  gap: 10px;
  align-items: center;
}

.thumb-preview {
  flex: 1;
  aspect-ratio: 16/9;
  background: #fff;
  border-radius: 4px;
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
  border: 2px solid transparent;
  transition: all 0.2s;
}

.thumbnail.active .thumb-preview {
  border-color: #38bdf8;
}

.thumb-title {
  font-size: 0.5rem;
  color: #000;
  font-weight: bold;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.thumb-lines .line {
  height: 2px;
  background: #e2e8f0;
  margin-bottom: 2px;
  width: 80%;
}

.thumb-num {
  font-size: 0.8rem;
  color: #64748b;
  width: 20px;
}

.slide-workspace {
  flex: 1;
  background: #0f172a;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px;
  position: relative;
}

.slide-canvas {
  width: 100%;
  max-width: 960px;
  aspect-ratio: 16/9;
  background: #fff;
  box-shadow: 0 0 50px rgba(0, 0, 0, 0.5);
  padding: 60px;
  color: #1e293b;
  display: flex;
  flex-direction: column;
}

.slide-content {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.editor-title {
  font-size: 2.5rem;
  font-weight: 700;
  border: none;
  background: transparent;
  outline: none;
  color: #1e293b;
  border-bottom: 2px solid transparent;
}

.editor-title:focus {
  border-bottom-color: #38bdf8;
}

.editor-body {
  flex: 1;
}

.editor-text-area {
  width: 100%;
  height: 100%;
  border: none;
  resize: none;
  font-size: 1.2rem;
  line-height: 1.6;
  color: #475569;
  outline: none;
  font-family: inherit;
}

.editor-controls {
  margin-top: 30px;
  display: flex;
  justify-content: space-between;
  width: 100%;
  max-width: 960px;
}

.nav-controls {
  display: flex;
  gap: 12px;
}

.nav-btn {
  background: rgba(30, 41, 59, 0.8);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: #fff;
  padding: 10px 20px;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
}

.nav-btn:hover:not(:disabled) {
  background: rgba(56, 189, 248, 0.2);
  border-color: #38bdf8;
}

.nav-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.export-btn {
  background: linear-gradient(135deg, #38bdf8, #6366f1);
  color: #fff;
  border: none;
  padding: 12px 24px;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 8px;
  box-shadow: 0 10px 20px rgba(56, 189, 248, 0.2);
  transition: all 0.2s;
}

.export-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 15px 30px rgba(56, 189, 248, 0.3);
}

.thumb-content-preview {
  margin-top: 4px;
  display: flex;
  flex-direction: column;
  gap: 3px;
}

.thumb-line {
  height: 2px;
  background: #cbd5e1;
  width: 100%;
  border-radius: 1px;
}

.thumb-line:nth-child(1) {
  width: 90%;
}
.thumb-line:nth-child(2) {
  width: 75%;
}
.thumb-line:nth-child(3) {
  width: 60%;
}

.slide-footer {
  margin-top: auto;
  padding-top: 20px;
  border-top: 1px solid #e2e8f0;
  display: flex;
  justify-content: space-between;
  font-size: 0.8rem;
  color: #94a3b8;
}

/* Animations */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

/* Mobile Responsiveness */
@media (max-width: 768px) {
  .header {
    padding: 0 20px;
  }

  .logo {
    font-size: 1.2rem;
  }

  .hero-text h1 {
    font-size: 2.5rem;
  }

  .step-container {
    padding: 20px 10px;
  }

  .input-box {
    flex-direction: column;
    padding: 12px;
  }

  .input-box input {
    padding: 12px;
    width: 100%;
    text-align: center;
  }

  .generate-btn {
    width: 100%;
    padding: 12px;
    margin-top: 8px;
  }

  .suggestions {
    flex-wrap: wrap;
    justify-content: center;
  }

  /* Step 2 Mobile */
  .outline-item {
    flex-direction: column;
  }

  .remove-btn {
    align-self: flex-end;
  }

  /* Step 3 Mobile */
  .editor-step {
    height: auto;
    min-height: calc(100vh - 70px);
  }

  .editor-layout {
    flex-direction: column-reverse; /* Sidebar at bottom or top? Let's put it at bottom for easier thumb access or top for context. Actually bottom is better for "tabs" style, but standard is usually separate. Let's just stack. */
    flex-direction: column;
  }

  .thumbnails-sidebar {
    width: 100%;
    height: 120px;
    flex-direction: row;
    overflow-x: auto;
    border-right: none;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    padding: 10px;
    order: 2; /* Move to bottom */
  }

  .slide-workspace {
    order: 1;
    padding: 20px 10px;
    height: auto;
    flex: 1;
  }

  .thumbnail {
    min-width: 160px;
    flex-direction: column;
    gap: 4px;
  }

  .thumb-preview {
    width: 100%;
  }

  .slide-canvas {
    padding: 20px;
    height: auto;
    min-height: 300px;
    aspect-ratio: auto;
  }

  .editor-title {
    font-size: 1.5rem;
  }

  .editor-text-area {
    font-size: 1rem;
  }

  .editor-controls {
    flex-direction: column;
    gap: 16px;
    align-items: center;
  }

  .nav-controls {
    width: 100%;
    justify-content: space-between;
  }

  .nav-btn {
    flex: 1;
  }

  .export-btn {
    width: 100%;
    justify-content: center;
  }
}
</style>
